# <center>Titanic Survival Analysis

## Project Overview

The Titanic dataset contains information about passengers aboard the RMS Titanic, including demographic characteristics, passenger class, fare, and survival status. This project uses exploratory data analysis (EDA) to investigate the factors associated with passenger survival.

The primary purpose of this analysis is to explore whether characteristics such as **passenger class, sex, age, and fare** were associated with differences in survival outcomes. Through data cleaning, descriptive statistics, and visualization, the project aims to identify meaningful patterns and relationships within the dataset.

## Objectives

The objectives of this project are to:

1. **Understand the dataset** by examining its structure, variables, data types, and descriptive statistics.
2. **Assess data quality** by identifying missing values, duplicate records, and potential inconsistencies.
3. **Explore passenger characteristics** such as age, sex, passenger class, and fare.
4. **Analyze survival rates** and determine how survival varied across different passenger groups.
5. **Investigate relationships** between passenger characteristics and survival outcomes using statistical summaries and visualizations.
6. **Identify key patterns and findings** that can help explain differences in survival among passengers.
7. **Communicate the findings** through clear visualizations and data-driven conclusions.

## General Project Outline

The analysis will follow the following workflow:

**1. Data Loading & Understanding**
Load the Titanic dataset and examine its dimensions, columns, data types, and initial records.

**2. Data Cleaning & Preparation**
Identify and address missing values, duplicates, and other data-quality issues before analysis.

**3. Exploratory Data Analysis**
Use descriptive statistics to understand the distribution of passenger characteristics and survival outcomes.

**4. Data Visualization**
Create appropriate visualizations such as bar charts, histograms, box plots, and count plots to explore patterns in the data.

**5. Survival Analysis**
Compare survival outcomes across variables such as sex, passenger class, age, and fare.

**6. Correlation & Relationships**
Examine relationships between relevant numerical variables and consider how they relate to survival.

**7. Key Findings & Conclusions**
Summarize the most important patterns identified during the analysis and distinguish observations supported by the data from assumptions that cannot be established through EDA alone.

## Guiding Question

> **What passenger characteristics were associated with survival on the Titanic?**

The analysis will use data and visual evidence to answer this question rather than assuming that any particular characteristic caused a passenger's survival or death.

## Data Loading and Understanding

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
df.shape

(891, 12)

In [10]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Data Cleaning

In [15]:
df.isnull().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

In [17]:
df.isnull().mean().sort_values(ascending=False)*100

Cabin          77.104377
Age            19.865320
Embarked        0.224467
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
dtype: float64

In [19]:
df.duplicated().sum()

0

In [23]:
df['Embarked'].mode()[0]

'S'

In [28]:
df["Embarked"] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [29]:
df.isnull().mean().sort_values(ascending=False)*100

Cabin          77.104377
Age            19.865320
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Embarked        0.000000
dtype: float64

In [30]:
df['Age'].mean()

29.69911764705882

In [33]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [34]:
df.isnull().mean().sort_values(ascending=False)*100

Cabin          77.104377
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Embarked        0.000000
dtype: float64

In [ ]:
df = df.drop('Cabin', axis = 1)

# Modern preferred method (reassignment)
#df = df.drop(columns=['Column_Name'])

# Dropping multiple columns at once
#df = df.drop(columns=['Column_A', 'Column_B'])

In [36]:
df.isnull().mean().sort_values(ascending=False)*100

PassengerId    0.0
Survived       0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64

In [37]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708,C